### ISSUE TITLE
Remove the dependency to LOV for every validation

### ISSUE THREAD

**Issue by jimkont** [AKSW/RDFUnit#34]
LOV is not very stable any more and results in failed RDFUnit executions.
instead generate and store the vocabulary metadata offline and save them as a Java resource which will be updated before each release

**Comment by rtroncy** [comment]
This is quite a strong statement. LOV had difficulties over the last few weeks due to attacks on OKFN servers and lack of response from the OKFN team. The LOV team aims definitively to be responsive and reliable. I suggest you discuss this issue with @pyvandenbussche

**Comment by jimkont** [comment]
LOV is a great service and I plan to continue depending on it.
What happens now is that RDFUnit calls LOV at the start of every evaluation and if it fails we cannot do any prefix dereferencing or auto schema discovery.
This task is about to cache the vocabularies locally for faster access and give the option to additionally call LOV for up-to-date data. So calling the online service would be optional.

I changed the issue title to make the statement less strong :)

**Comment by jimkont** [comment]
BTW, @pyvandenbussche I again had to put the internal LOV URI to get results from the endpoint https://github.com/AKSW/RDFUnit/commit/6d0a0be2c055c2ccca08328f3a43eb0e0fa5f0c3 :
http://s110.okserver.org:3030/lov/sparql

**Comment by pyvandenbussche** [comment]
Hi Dimitris,

that sounds like a very sounded approach. Having a cache in case LOV is not available and in case id is, run the query live. 

I will look at the URI again. You can as well now consider using the LOV Linked Data Fragment https://plus.google.com/+PierreYvesVandenbussche/posts/Bb3dRqCp3hi

Cheers.

**Comment by jimkont** [comment]
FYI, I already had caching on the client with 1 week expiration and this
issue is about putting the cache directly in the repo

**Comment by roland-c** [comment]
Since LOV has been down lately the adress of the sparql endpoint is changed, also an additional graph specification is needed in the query. The following changes must be made to fix this:

https://github.com/AKSW/RDFUnit/blob/master/rdfunit-core/src/main/java/org/aksw/rdfunit/Utils/RDFUnitUtils.java#L105 >>         
Source lov = new EndpointTestSource("lov", "http://lov.okfn.org", "http://lov.okfn.org/dataset/lov/sparql", Arrays.asList("http://lov.okfn.org/dataset/lov"), null);

https://github.com/AKSW/RDFUnit/blob/master/rdfunit-core/src/main/java/org/aksw/rdfunit/Utils/RDFUnitUtils.java#L129 >>                            
"WHERE{ GRAPH <http://lov.okfn.org/dataset/lov>{ \n" +

https://github.com/AKSW/RDFUnit/blob/master/rdfunit-core/src/main/java/org/aksw/rdfunit/Utils/RDFUnitUtils.java#L134 >>                          
 "}} \n" +

**Comment by pyvandenbussche** [comment]
Hi Dimitris,

I've cleaned the way to access LOV sparql endpoint. I blocked the internal URL and now the only URL for LOV endpoint is: http://lov.okfn.org/dataset/lov/sparql

This URL will not change in the future.

**Comment by jimkont** [comment]
Hi @pyvandenbussche 
I changed the new URL and I get the following error
```
java.lang.RuntimeException: com.hp.hpl.jena.query.QueryException: Endpoint returned Content-Type: text/html which is not currently supported for SELECT queries
```
also make sure you allow the additional url parameters `default-graph-uri` & `named-graph-uri` to be passed to the internal endpoint

**Comment by jimkont** [comment]
IIRC we had the same problem before and you told be it was a jena v2.11 vs v2.12+ issue

**Comment by pyvandenbussche** [comment]
I try to find back our discussion on that topic to see what was the solution :)

**Comment by AndreAga** [comment]
@jimkont The LOV SPARQL Endpoint seems to be unattainable.

**Comment by pyvandenbussche** [comment]
Now everything is working using the permanent URL: http://lov.okfn.org/dataset/lov/sparql
Thanks @jimkont for your help.
